### PR TITLE
Fix pytest-socket raises IndexError with httpx

### LINKED ISSUE #84: pytest-socket raises IndexError when used with httpx
pytest-socket raises IndexError when used with httpx:

```python
cls = <class 'pytest_socket.disable_socket.<locals>.GuardedSocket'>, args = ()
kwargs = {'family': <AddressFamily.AF_INET: 2>, 'proto': 6, 'type': <SocketKind.SOCK_STREAM: 1>}

    def __new__(cls, *args, **kwargs):
        try:
>           is_unix_socket = args[0] == socket.AF_UNIX
E           IndexError: tuple index out of range

.venv/lib/python3.9/site-packages/pytest_socket.py:89: IndexError
```

<details>
<summary>See full stack trace</summary>
<br>

```python
.venv/lib/python3.9/site-packages/httpx/_client.py:1736: in get
    return await self.request(
.venv/lib/python3.9/site-packages/httpx/_client.py:1513: in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
.venv/lib/python3.9/site-packages/httpx/_client.py:1600: in send
    response = await self._send_handling_auth(
.venv/lib/python3.9/site-packages/httpx/_client.py:1628: in _send_handling_auth
    response = await self._send_handling_redirects(
.venv/lib/python3.9/site-packages/httpx/_client.py:1665: in _send_handling_redirects
    response = await self._send_single_request(request)
.venv/lib/python3.9/site-packages/httpx/_client.py:1702: in _send_single_request
    response = await transport.handle_async_request(request)
.venv/lib/python3.9/site-packages/httpx/_transports/asgi.py:152: in handle_async_request
    await self.app(scope, receive, send)
...
.venv/lib/python3.9/site-packages/httpx/_client.py:1513: in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
.venv/lib/python3.9/site-packages/httpx/_client.py:1600: in send
    response = await self._send_handling_auth(
.venv/lib/python3.9/site-packages/httpx/_client.py:1628: in _send_handling_auth
    response = await self._send_handling_redirects(
.venv/lib/python3.9/site-packages/httpx/_client.py:1665: in _send_handling_redirects
    response = await self._send_single_request(request)
.venv/lib/python3.9/site-packages/httpx/_client.py:1702: in _send_single_request
    response = await transport.handle_async_request(request)
.venv/lib/python3.9/site-packages/httpx/_transports/default.py:291: in handle_async_request
    resp = await self._pool.handle_async_request(req)
.venv/lib/python3.9/site-packages/httpcore/_async/connection_pool.py:248: in handle_async_request
    raise exc
.venv/lib/python3.9/site-packages/httpcore/_async/connection_pool.py:232: in handle_async_request
    response = await connection.handle_async_request(request)
.venv/lib/python3.9/site-packages/httpcore/_async/connection.py:90: in handle_async_request
    raise exc
.venv/lib/python3.9/site-packages/httpcore/_async/connection.py:67: in handle_async_request
    stream = await self._connect(request)
.venv/lib/python3.9/site-packages/httpcore/_async/connection.py:115: in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
.venv/lib/python3.9/site-packages/httpcore/backends/auto.py:23: in connect_tcp
    return await self._backend.connect_tcp(
.venv/lib/python3.9/site-packages/httpcore/backends/asyncio.py:97: in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
.venv/lib/python3.9/site-packages/anyio/_core/_sockets.py:180: in connect_tcp
    await event.wait()
.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py:567: in __aexit__
    raise exceptions[0]
.venv/lib/python3.9/site-packages/anyio/_core/_sockets.py:127: in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py:1499: in connect_tcp
    await get_running_loop().create_connection(StreamProtocol, host, port,
/usr/lib/python3.9/asyncio/base_events.py:1041: in create_connection
    sock = await self._connect_sock(
/usr/lib/python3.9/asyncio/base_events.py:938: in _connect_sock
    sock = socket.socket(family=family, type=type_, proto=proto)
```
</details>

I'm not sure exactly why this happens but I'm guessing it is somehow related to anyio rather than httpx. You can reproduce the issue with this code:

```python
import pytest
import httpx


@pytest.fixture(autouse=True)
def anyio_backend():
    return "asyncio"

async def test_httpx():
    async with httpx.AsyncClient() as client:
        await client.get("http://www.example.com/")
```

### PR DESCRIPTION
**Pull request by ollipa**
Closes #84

### CODE REVIEW

**Comment by miketheman** [comment]
Thanks for the detailed report! I can't help but wonder that there's something else going on here - I've seen this behavior somewhere else and I can't recall what triggered it, but I don't think it was specific to the httpx library.

I think an alternate solution could be:

```python
            try:
                is_unix_socket = args[0] == socket.AF_UNIX if args else None
            except AttributeError:
```

which would likely solve the same issue, but I think your approach is more Pythonic.

i wish I remembered how that was triggered, so would be able to not have to include another external package for testing, but until I can recall, this will do. Thanks!

**Comment by ljodal** [comment]
@miketheman This is also triggered by [`asyncpg`](https://magicstack.github.io/asyncpg/current/index.html). Looks like AsyncIO is using kwargs-only in the `socket.socket()` call [here](https://github.com/python/cpython/blob/main/Lib/asyncio/base_events.py#L933).

```
/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/asyncio/base_events.py:641: in run_until_complete
    return future.result()
.venv/lib/python3.10/site-packages/pytest_asyncio/plugin.py:123: in setup
    res = await gen_obj.__anext__()
tests/conftest.py:52: in _connection
    connection = await asyncpg.connect()
.venv/lib/python3.10/site-packages/asyncpg/connection.py:2085: in connect
    return await connect_utils._connect(
.venv/lib/python3.10/site-packages/asyncpg/connect_utils.py:881: in _connect
    return await _connect_addr(
.venv/lib/python3.10/site-packages/asyncpg/connect_utils.py:781: in _connect_addr
    return await __connect_addr(params, timeout, True, *args)
.venv/lib/python3.10/site-packages/asyncpg/connect_utils.py:825: in __connect_addr
    tr, pr = await compat.wait_for(connector, timeout=timeout)
.venv/lib/python3.10/site-packages/asyncpg/compat.py:66: in wait_for
    return await asyncio.wait_for(fut, timeout)
/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/asyncio/tasks.py:445: in wait_for
    return fut.result()
.venv/lib/python3.10/site-packages/asyncpg/connect_utils.py:691: in _create_ssl_connection
    tr, pr = await loop.create_connection(
/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/asyncio/base_events.py:1040: in create_connection
    sock = await self._connect_sock(
/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/asyncio/base_events.py:937: in _connect_sock
    sock = socket.socket(family=family, type=type_, proto=proto)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cls = <class 'pytest_socket.disable_socket.<locals>.GuardedSocket'>, args = ()
kwargs = {'family': <AddressFamily.AF_INET6: 10>, 'proto': 6, 'type': <SocketKind.SOCK_STREAM: 1>}

    def __new__(cls, *args, **kwargs):
        try:
>           is_unix_socket = args[0] == socket.AF_UNIX
E           IndexError: tuple index out of range

.venv/lib/python3.10/site-packages/pytest_socket.py:89: IndexError
```

**Comment by miketheman** [comment]
@ljodal Thanks for the report - can you by any change try out the plugin with the lasted code on `main`? The behavior has changed, and I'm planning on releasing 0.50.0 soon.

**Comment by ljodal** [comment]
@miketheman It works with latest main.

I'd argue that as `family` is specified as part of `kwargs` here a better fix in this case would be to do something like this:

```python
if 'family' in kwargs:
    family = kwargs['family']
elif args:
    family = args[0]
else:
    # This seems to be the default?
    family = socket.AF_INET

try:
    is_unix_socket = family == socket.AF_UNIX
except AttributeError:
    is_unix_socket = False
```

Or at least adding a check in kwargs:

```python
try:
    family = kwargs['family'] if 'family' in kwargs else args[0]
    is_unix_socket = family == socket.AF_UNIX
except (AttributeError, IndexError):
    is_unix_socket = False

**Comment by miketheman** [comment]
@ljodal glad to hear it! To be clear, the code in the PR is not the final fix - the kwargs have been updated to match the parent class' signature in https://github.com/miketheman/pytest-socket/pull/75 and has been since extracted to a common helper function `_is_unix_socket()`.

**Comment by ljodal** [comment]
Ah, great! Should've checked `main`, sorry!

**Pull request merged**
