### PR TITLE
chore(allow_hosts): Use getaddrinfo instead of gethostbyname

### PR DESCRIPTION
**Pull request by hasier**
https://github.com/miketheman/pytest-socket/pull/189 introduced hostname resolution to allow passing actual host names rather than IPs to the allowlist. This used `getaddrinfo` to get the actual IP addresses of hosts, but this is limited to only 1 IPv4 address result, where the address may have more than 1, or maybe even IPv6. This is a [limitation stated in the Python docs](https://docs.python.org/3/library/socket.html#socket.gethostbyname), and the suggested alternative is to use `gethostbyname`.

I assumed the same tests from https://github.com/miketheman/pytest-socket/pull/189 should apply, as the functionality itself is not changing. Please let me know if there are any other tests you'd like to see.

As a side effect, I have also slightly improved the error message for `SocketConnectBlockedError`, as I found it'd help me with some of the tests I've been building lately. Where the error message used to be like
```
A test tried to use socket.socket.connect() with host "172.217.169.3" (allowed: "google.com").
```
now will look more like
```
A test tried to use socket.socket.connect() with host "172.217.169.3" (allowed: "google.com (172.217.169.14)").
```

### CODE REVIEW

**Comment by hasier** [comment]
Seems like https://httpbin.org/ is having some issues, it's 504ing in the browser for me as well. I'll keep an eye on it to see if we can rerun when it's stable again.

**Comment by hasier** [comment]
@miketheman https://httpbin.org/ seems to be better now, feel free to approve the test run whenever you prefer 🙂

**Comment by miketheman** [comment]
@hasier Thanks for working through this - glad to see the existing behaviors are not affected.
There's enough code changes that don't have any new tests - can you please add some in another commit to detail what the behaviors that you're seeing trigger these new code paths?

**Comment by hasier** [comment]
> @hasier Thanks for working through this - glad to see the existing behaviors are not affected. There's enough code changes that don't have any new tests - can you please add some in another commit to detail what the behaviors that you're seeing trigger these new code paths?

@miketheman the underlying behaviour was not changed, so I could only think of a test that used a hostname directly as an argument, which I added in https://github.com/miketheman/pytest-socket/pull/209/commits/75c0a8fedaeeed1db6d54812e8b8fadc62f2c815. Let me know what you think 🙂

**Comment by hasier** [comment]
@miketheman thanks for re-running the tests! Any thoughts on the changes? 🙂

**Comment by hasier** [comment]
@miketheman any chance you can take a look at this again, whenever you have a bit of time? 😊

**Comment by hasier** [comment]
@miketheman I have updated the PR with the changes in `main`, could approve the workflow run and review again whenever you have some time, please? Thanks!

**Comment by hasier** [comment]
@miketheman seems like HTTPBin is somewhat stable now (at least for the few request I just tried), maybe we can re-run CI one last time? 🤞

**Comment by miketheman** [comment]
@hasier Thankfully, httpbin played nice today.
We got an interesting error: https://github.com/miketheman/pytest-socket/actions/runs/5305161721/jobs/9601944686#step:6:157

> pytest_socket.SocketConnectBlockedError: A test tried to use socket.socket.connect() with host "192.30.255.113" (allowed: "github.com (192.30.255.112)").

Is this due to now how the functionality works with multiple DNS addresses?

**Comment by hasier** [comment]
> @hasier Thankfully, httpbin played nice today. We got an interesting error: https://github.com/miketheman/pytest-socket/actions/runs/5305161721/jobs/9601944686#step:6:157
> 
> > pytest_socket.SocketConnectBlockedError: A test tried to use socket.socket.connect() with host "192.30.255.113" (allowed: "github.com (192.30.255.112)").
> 
> Is this due to now how the functionality works with multiple DNS addresses?

Thanks for rerunning it @miketheman!

Hmm interesting, not sure it's directly related to the new functionality, the tests in the rest of Python versions succeeded, and it did locally for me too, so the resolution seems accurate most of the time 🤔  The new way of resolving IPs should simply yield multiple results, as opposed to just 1 from the previous method, but in the test there was only 1 result returned (note how there's only 1 IP allowed in the message `(allowed: "github.com (192.30.255.112)")`). Considering we are reaching out to a real address and the OS will be resolving DNSs each time, maybe we are more liable to this sort of tiny variations as Github will regularly change their external IPs, which will make this test flaky...

I have changed the test to check values only against `"localhost"`, similar to what other tests do, also ensuring that it still resolves the hostname to its `127.0.0.1` and `::1` IPs to test the new functionality. This way we avoid the flakiness of a real address changing IPs, while still ensuring that `"localhost"` is correctly resolved to IP addresses. wdyt?

**Comment by miketheman** [comment]
@hasier thanks again for persisting! It's been a bit rocky for sure, but I think we got to a better solution overall.

**Comment by hasier** [comment]
Amazing, thanks very much to you @miketheman for bearing with all these reruns! 🙇

**Pull request merged**
