### PR TITLE
feat: support cidr blocks in --allow-hosts

### PR DESCRIPTION
**Pull request by emhagman**
This feature allows `--allow-hosts` to support CIDR blocks. This is useful inside Docker since different services can get any range of IPs (typically on 172.17.0.0/16 or 172.20.0.0/16) and pytest-socket doesn't support hostnames.

I can also add hostname support if we think that is useful.

### CODE REVIEW

**Comment by emhagman** [comment]
> Any chance of getting this merged? Would absolutely love this feature for our CI pipelines! Alternatively #80 would also solve this issue for us.

We've been pointing to our fork. Unfortunately it doesn't seem these pull requests are looked at

**Comment by miketheman** [comment]
> Unfortunately it doesn't seem these pull requests are looked at.

They do get looked at - this specific one is failing a check which would need to be resolved.

**Comment by emhagman** [comment]
> > Unfortunately it doesn't seem these pull requests are looked at.
> 
> They do get looked at - this specific one is failing a check which would need to be resolved.

A complexity check off by one...? OK, I can fix it.

**Comment by emhagman** [comment]
@miketheman should be all set now!

**Comment by mgaitan** [comment]
@miketheman @emhagman how could I help to get this merged? Should I open a new PR fixing the conflict ?

**Comment by djanowski** [comment]
@miketheman Any chance of getting this merged, or @mgaitan's alternative #185?

**Comment by emhagman** [comment]
I'd just take https://github.com/miketheman/pytest-socket/pull/185 over this. Don't want to fix conflicts, this has been open forever. We've just been using our fork forever now.

**Pull request closed without merging**
